# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_authorized',
        ),
        migrations.AddField(
            model_name='profile',
            name='free_ballots',
            field=models.IntegerField(default=0),
        ),
    ]
