# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180618_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_new_customer',
        ),
    ]
