# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_name', models.CharField(max_length=50, unique=True)),
                ('ballot_url', models.SlugField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('expiry_date', models.DateTimeField(verbose_name='Expires on')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Ballot Papers',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('ballot_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BallotPaper')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=250)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
