# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ballotpaper_show_results_to_public'),
        ('polls', '0002_auto_20180513_2254'),
    ]

    operations = [
    ]
