# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180131_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotpaper',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='ballotpaper',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='ballotpaper',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='ballotpaper',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
