# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_merge_20180522_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotpaper',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ballotpaper',
            name='is_not_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ballotpaper',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
