# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ballotpaper_can_add_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotpaper',
            name='has_email_delivery',
        ),
        migrations.RemoveField(
            model_name='ballotpaper',
            name='has_text_delivery',
        ),
        migrations.AddField(
            model_name='ballotpaper',
            name='uploaded_emails',
            field=models.BooleanField(default=False),
        ),
    ]
