# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180205_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotpaper',
            name='active',
        ),
    ]
