# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180522_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballotpaper',
            old_name='is_not_opened',
            new_name='is_not_open',
        ),
    ]
