# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_ballotpaper_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotpaper',
            name='is_image_ballot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
