# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180329_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads/'),
        ),
    ]
