# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180523_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotpaper',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='ballotpaper',
            name='is_not_open',
        ),
    ]
