# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180329_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='image',
            new_name='photo',
        ),
    ]
