# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180329_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballotpaper',
            old_name='is_image_ballot',
            new_name='is_photo_ballot',
        ),
    ]
