# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_ballotpaper_show_results_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotpaper',
            name='email_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ballotpaper',
            name='text_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ballotpaper',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
