# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 16:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180329_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='photo',
            field=models.ImageField(blank=True, upload_to=django.core.files.storage.FileSystemStorage(location='media/uploads')),
        ),
    ]
