# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180329_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='photo',
            field=models.ImageField(blank=True, default='media/uploads/DZeE0moXUAY8T7X.jpg', upload_to='media/uploads/'),
        ),
    ]
