# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180330_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
