# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180331_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='photo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
