# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180331_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotpaper',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ballotpaper',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
