# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_ballotpaper_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('ballot_paper', 'category_name')]),
        ),
    ]
