# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0017_auto_20180417_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ballotpaper',
            unique_together=set([('ballot_name', 'created_by')]),
        ),
    ]
