# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20180419_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotpaper',
            name='ballot_name',
            field=models.CharField(max_length=50),
        ),
    ]
