# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20180419_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('category', 'choice')]),
        ),
    ]
