# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20180425_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotpaper',
            name='is_active',
        ),
    ]
